api:
  version: 1.0

server:
  port: 2000

spring:
  main:
    banner-mode: "off"

springdoc:
  pathsToMatch: /api/**
  api-docs.path: /spec/index
  model-converters.pageable-converter.enabled: true

services:
  external:
    csv:
      brands:
        url: ${BRANDS_CSV_URL:https://static.dwcdn.net/data/4yMOy.csv}
      brandImages:
        url: ${BRAND_IMAGES_CSV_URL:https://docs.google.com/spreadsheets/d/1eX7JGrhg9Jagl0zVj3_NkRfhZmpKDbDbq8z4e-kil38/gviz/tq?tqx=out:csv&sheet=brand-images}
      products:
        url: ${PRODUCTS_CSV_URL:https://docs.google.com/spreadsheets/d/1eX7JGrhg9Jagl0zVj3_NkRfhZmpKDbDbq8z4e-kil38/gviz/tq?tqx=out:csv&sheet=products}
      actions:
        url: ${ACTIONS_CSV_URL:https://docs.google.com/spreadsheets/d/1eX7JGrhg9Jagl0zVj3_NkRfhZmpKDbDbq8z4e-kil38/gviz/tq?tqx=out:csv&sheet=actions}

cache:
  brands:
    name: brands
    cron: "0 0 * * * *"
