server:
  port: 2000

spring:
  main:
    banner-mode: "off"

springdoc:
  pathsToMatch: /api/**
  api-docs.path: /spec/index
  model-converters.pageable-converter.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches

services:
  external:
    csv:
      brands:
        url: ${BRANDS_CSV_URL:https://docs.google.com/spreadsheets/d/1XPEuCgVmkOHUcYIqSmJ8lFIQPaK2F-tV738xsj5muWQ/gviz/tq?tqx=out:csv&sheet=brands}
      products:
        url: ${PRODUCTS_CSV_URL:https://docs.google.com/spreadsheets/d/1XPEuCgVmkOHUcYIqSmJ8lFIQPaK2F-tV738xsj5muWQ/gviz/tq?tqx=out:csv&sheet=products}
      grades:
        url: ${GRADES_CSV_URL:https://docs.google.com/spreadsheets/d/1XPEuCgVmkOHUcYIqSmJ8lFIQPaK2F-tV738xsj5muWQ/gviz/tq?tqx=out:csv&sheet=grades}

cache:
  cron: "${CACHE_CRON:0 0 * * * *}"

admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin}
