server:
  port: 2000

spring:
  main:
    banner-mode: "off"

springdoc:
  pathsToMatch: /api/**
  api-docs.path: /spec/index
  model-converters.pageable-converter.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches

services:
  external:
    csv:
      brands:
        url: http://brands.csv.url.com
      ukrainianBrands:
        url: http://ukrainian-brands.csv.url.com
      products:
        url: http://products.csv.url.com
      grades:
        url: http://grades.csv.url.com

cache:
  cron: "0 0 * * * *"

admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin}
